'use client';

import { highlight } from '@/lib/helpers/highlight';
import styles from './JsonDrawer.module.css';

interface JsonDrawerProps {
  step: number | null;
  stepLabel: string;
  data: unknown;
  onClose: () => void;
}

export default function JsonDrawer({ step, stepLabel, data, onClose }: JsonDrawerProps) {
  const isOpen = step !== null && data !== undefined;

  if (!isOpen) return null;

  return (
    <div className={styles.drawer}>
      <div className={styles.header}>
        <span className={styles.title}>
          Step {step} — {stepLabel}
        </span>
        <button type="button" className={styles.close} onClick={onClose} aria-label="Close">
          ✕
        </button>
      </div>
      {/* biome-ignore lint/security/noDangerouslySetInnerHtml: content is generated by our own highlight() sanitiser */}
      <div className={styles.body} dangerouslySetInnerHTML={{ __html: highlight(data) }} />
    </div>
  );
}
